name: ci

on:
  push:
    branches: [ wip ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - name: Build
        run: mvn -q -DskipTests clean package
      - name: Unit + Integration tests
        run: mvn -q test
      - name: Pact (consumer)
        run: mvn -q -pl orchestrator-service -Ppact test
      - name: Pact (provider verify)
        run: mvn -q -pl data-broker-service -Ppact verify
      - name: Upload pacts
        uses: actions/upload-artifact@v4
        with:
          name: pacts
          path: orchestrator-service/target/pacts
